services:
  - type: web
    name: HireMeter
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
